### ISSUE TITLE
Documentation Update: When Upgrading/Installing Run Migrations

### ISSUE THREAD

**Issue by jvanderaa** [networktocode/ntc-netbox-plugin-onboarding#105]
### Environment
* Python version:  Python 3.7.7
* NetBox version:  2.8.9
* ntc-netbox-plugin-onboarding version:  2.0.0

### Steps to Reproduce
1. Change the pip install from 1.3 to 2.0
2. Start server
3. Check on devices, attempt to use the API

### Expected Behavior

Everything should be working in a normal state

### Observed Behavior

500 errors when using the API and programming errors when navigating to a device in NetBox

### Resolution

Run migrations after installing the update

**Comment by dgarros** [comment]
I think it's already mentioned in the readme (Line 54)
Maybe should add a brief section about upgrade
