### ISSUE TITLE
Onboarding Device Via Name Fails with 2.0

### ISSUE THREAD

**Issue by jvanderaa** [networktocode/ntc-netbox-plugin-onboarding#106]
### Environment
* Python version:  3.7.7
* NetBox version:  2.8.9
* ntc-netbox-plugin-onboarding version: 2.0.0

### Steps to Reproduce
1. Create a new onboarding task with DNS name of "rtr-branch"
2. Verify DNS resolution works
3. Find that the onboarding task is reporting `['Invalid IP address format: rtr-branch']`

### Expected Behavior

Onboarding to occur

### Observed Behavior

['Invalid IP address format: rtr-branch']

**Comment by mzbroch** [comment]
@jvanderaa Please provide us with exact logs of this issue - without a traceback I can not resolve this issue

**Comment by mzbroch** [comment]
This is a warning message and should not prevent the task from running.

Existing devices are identified by IP lookups against `primary_ip4__address__net_host`. This function currently does not work with FQDNs and this was the initial intention. I am open for seeing a PR with this function :-)
