### ISSUE TITLE
ERROR device type xxxx already exists for vendor xxxx

### ISSUE THREAD

**Issue by GeertReijnders** [networktocode/ntc-netbox-plugin-onboarding#109]
### Environment
* Python version:  3.6.9
* NetBox version:  2.9.7
* ntc-netbox-plugin-onboarding version:  2.0.0

### Steps to Reproduce
1. Start the plugin via the web interface
2. Fill in the IP address of the device and the SSH credentials and click on create. Everything else is in its default state.

My plugin config is configuration.py is:

PLUGINS = ['netbox_onboarding']

I expect the device to be created.

after a while, I see the following message:
ERROR device type xxxx already exists for vendor xxxx

**Comment by mzbroch** [comment]
This error condition is typically raised whenever a Device Type (NetBox object) recognized on a network device has a different manufacturer assigned (in NetBox) than manufacturer recognized through automation. 

Plugin uses the existing NetBox objects - including Device Type and Manufacturers - please validate existing database objects and update with details

**Comment by GeertReijnders** [comment]
I already created the Vendor Cisco Systems with all the device types before I ran into this script. This script creates the Vendor for me (Cisco) and looks for the device type, which already exists. So I changed the vendor name to Cisco and now the script works fine!

This is something I wasn't aware of. Thanks for the explanation.
