### ISSUE TITLE
Once installed Ntc Onboarding2, getting bad gateway 502 error

### ISSUE THREAD

**Issue by nanisyako** [networktocode/ntc-netbox-plugin-onboarding#111]
### Environment
* Python version:  3.6.8
* NetBox version:  2.9.3
* ntc-netbox-plugin-onboarding version:  2.0

### Steps to Reproduce
1. installed netbox 2 with pip
2. enabled it in configuration.py and restarted netbox and netbox-rq
3.run migrate.py then restart netbox and netbox-rq since were not able to see onboarding plugin tab. 

### Expected Behavior
To see onboarding plugin tab in the main page

### Observed Behavior
502 badgateway

**Comment by dgarros** [comment]
@nanisyako if you're getting a `502 badgateway` error it means the netbox service is not starting correctly so there must be some logs available that will provide some information.

Please can you provide the logs form the `netbox` and `netbox-rq` services ? and also provide the part of your `configuration.py` file related to plugins ? (PLUGINS & PLUGINS_CONFIG)

thanks

**Comment by nanisyako** [comment]
The issue was I insatelled ntc-onbarding with pip but it seems I had to run the pip from venv.
