### ISSUE TITLE
Newly added onboard tasks do not start after adding them.

### ISSUE THREAD

**Issue by mattwalter-cadenzallc** [networktocode/ntc-netbox-plugin-onboarding#116]
### Environment
* Python version:  Python 3.8.6
* NetBox version:  2.9.10
* ntc-netbox-plugin-onboarding version: 2

Newly added onboard tasks do not start after adding them.

### Steps to Reproduce
1. Add device onboard task
2. Review onboard tasks and see no status.

### Expected Behavior
Onboard task to start and process.

### Observed Behavior
Onboard task does not start after adding.

Admin -> Background Tasks -> Default Queue -> shows failed jobs with message:
RuntimeError: Model class netbox_onboarding.models.OnboardingTask doesn't declare an explicit app_label and isn't in an application in INSTALLED_APPS.

**Comment by dgarros** [comment]
@mattwalter-cadenzallc looks like the onboarding plugin package is not properly installed on the worker. 
have you restarted the worker(s) after the installation of the plugin ?

**Comment by mattwalter-cadenzallc** [comment]
Correct - it's been restarted.

**Comment by mattwalter-cadenzallc** [comment]
@dgarros Thanks for the help in troubleshooting this... my error was this:

I am using the netbox-docker project for this deployment and moved my volume definitions into docker-compose.override.yml and did not carry over the netbox-worker -> netbox yaml anchors that keeps netbox-worker using the same volumes as netbox container. So while the ntc_onboarding module was present in worker, it wasn't in the configuration to load.
