### ISSUE TITLE
Plugin not working with latest Netbox release.

### ISSUE THREAD

**Issue by o4sis** [networktocode/ntc-netbox-plugin-onboarding#117]
### Environment
* Python version:  3.6.8
* NetBox version:  v2.10.1
* ntc-netbox-plugin-onboarding version:  2.0.0

### Steps to Reproduce
1. Netbox 2.9.9 -> 2.10

### Expected Behavior
Rolled dice hoping it would work, doesn't work. Not complaining, just letting team know in case they were not aware.

### Observed Behavior
Cannot enable plugin with changes to 2.10 netbox database schema. It does not understand the new bulk features.

**Comment by mzbroch** [comment]
Thank you for reporting this issue - currently supported NetBox releases are 2.8 and 2.9
Issue #118 will be used to track activity of adding support for NetBox 2.10
