### ISSUE TITLE
Issue on installing release 1.3 to netbox 2.8.9 

### ISSUE THREAD

**Issue by roadmnet** [networktocode/ntc-netbox-plugin-onboarding#123]
I've an issue installing release 1.3 into netbox 2.8.0. I went through these steps:

cd /opt/netbox
source venv/bin/activate
pip install ntc-netbox-plugin-onboarding

pip list | grep ntc
"venv) [root@sever netbox]# pip list | grep ntc
ntc-netbox-plugin-onboarding 1.3.0"

systemctl restart netbox netbox-rq

After added this:  PLUGINS = ["netbox_onboarding"]

python3 manage.py migrate shows me this:
" (venv) [root@server netbox]# python3 manage.py migrate 
python3: can't open file 'manage.py': [Errno 2] No such file or directory"

There is no manage.py in /opt/netbox, but there is one in /opt/netbox/netbox. 

I tried this #python3 netbox/manage.py migrate
" (venv) [root@racktables netbox]# python3 netbox/manage.py migrate
Operations to perform:
  Apply all migrations: admin, auth, circuits, contenttypes, dcim, extras, ipam, netbox_onboarding, secrets, sessions, taggit, tenancy, users, virtualization
Running migrations:
  No migrations to apply."

Everything seems to be fine, but if I do this “systemctl restart netbox netbox-rq” now, the netbox site becomes unavailable. I need to remove the PLUGINS = ["netbox_onboarding"], then restart netbox to regain access.

What I am missing? Greatly appreciated for any suggestions to check. 

-Thomas

**Comment by mzbroch** [comment]
Unfortunately you need to troubleshoot the loading process of the plugin and provide us with more information - consider starting with `manage.py nbshell` and importing plugin manually from an interpreter. Before you do this, I also highly recommend using latest version of the plugin instead of legacy 1.3 release.
