### ISSUE TITLE
Invalid slug generation

### ISSUE THREAD

**Issue by karrots** [networktocode/ntc-netbox-plugin-onboarding#36]
When importing devices types slugs can be created with improper characters. Example
![image](https://user-images.githubusercontent.com/6307688/82502565-a5857880-9ab4-11ea-87fa-0ad8bcb39496.png)

**Comment by dgarros** [comment]
Thanks @karrots for reporting this issue, should be fixed by #37 thanks to @whitej6 
we'll publish a new release soon
