### ISSUE TITLE
Onboard Existing Devices

### ISSUE THREAD

**Issue by ryanmerolle** [networktocode/ntc-netbox-plugin-onboarding#40]
Add functionality to update existing devices.

I need to hash out the specifics, but it would be useful to update devices that are already in NetBox based on a hostname and site match.

Some people have workflows where they rack devices or at least mark said devices as planned in a rack.  It could be useful to allow you to complete the onboard process of these devices even though they are technically in NetBox.

**Comment by ryanmerolle** [comment]
This could be a fairly involved feature given the plugin would have to show conflicts, changes for approval, and other guard rails so the user can approve the changes to the existing device(s).

**Comment by ryanmerolle** [comment]
This actually works if the name and site match.  This may or may not be intended.

**Comment by dgarros** [comment]
I think this feature request is covered by #45 
Initially it was just about adding a default status but at the end, the new code support the re-onboarding of existing devices, specifically : platform, serial, interface and mgmt ip will be updated on an existing device if the name and the site matches
