### ISSUE TITLE
Add option for onboard process to add all interfaces

### ISSUE THREAD

**Issue by ryanmerolle** [networktocode/ntc-netbox-plugin-onboarding#42]
NetBox Cersion: 2.8.4
OnBoarding Plugin Version: 1.0.0
Python Version: 3.6.8
NAPALM Version: 3.0.1
Arista EOS Version: 4.22.5M

It looks like at least with EOS, when you onboard a device only the interface associated to the IP used to onboard the device is created with the new device.

**Comment by dgarros** [comment]
Hi @ryanmerolle,  
This is the expected behavior, we have a section for it in the [FAQ](https://github.com/networktocode/ntc-netbox-plugin-onboarding/blob/master/FAQ.md#does-this-plugin-support-the-discovery-and-the-creation-of-all-interfaces-and-ip-addresses-)

**Comment by ryanmerolle** [comment]
Ha, well I should have seen it.  It’s even clearly in the README.  This could be a feature request for a checkbox to get all interfaces and IPs.

**Comment by ryanmerolle** [comment]
Seeing how this is out of scope for the plugin.  If people want this feature they can try this project out https://github.com/scaleway/netbox-netprod-importer
