### ISSUE TITLE
Allow onboards by FQDN and not just IP

### ISSUE THREAD

**Issue by ryanmerolle** [networktocode/ntc-netbox-plugin-onboarding#43]
Allow onboards by FQDN and not just IP

**Comment by dgarros** [comment]
I was thinking about this one too, I agree it would be useful but won't be able to auto-discover the management interface and IP address.

In this case, we should have an option to use the FQDN as the name of the device instead of the hostname.

**Comment by ryanmerolle** [comment]
There could be several ways to handle this in the onboard form with a drop down or checkbox.

Some people may use the FQDN as being  an OOB or IB mgmt address.  In that case you would want the resolved IP to be used for the management IP.  You could even have said FQDN inputted into the created IP object itself.

**Comment by jvanderaa** [comment]
If there is a FQDN, could a lookup of the FQDN to get the address and then use that as the primary IP address?
