### ISSUE TITLE
Pass netbox plugin settings for default mappings

### ISSUE THREAD

**Issue by ryanmerolle** [networktocode/ntc-netbox-plugin-onboarding#49]
### Environment
* Python version:  3.7.7
* NetBox version:  2.8.5
* ntc-netbox-plugin-onboarding version:  Example: 1.0.0

### Proposed Functionality

The NetBox plugins function has a way to pass cars from the NetBox config file for the deployed plugin.  It would be useful to use this function to pass platform and manufacturer name mappings.  Example:
```
 PLUGINS_CONFIG = {
   "netbox_onboarding": {
      platform_map: {
            "arista_eos": "eos",
            "cisco_ios": "ios",
     },
      manufacturer_map: {
            "Arista": "Arista Networks",
            "Cisco": "Cisco Networks",
     },
   }
 }
```

### Use Case

This would be useful if individuals did not want to rename their current platform and manufacturers or the associated slugs.  It may seem like a minor hurtle for some people, but their automation may already match a slug they set already or they may want the slug to exactly match the napalm driver.

**Comment by dgarros** [comment]
Thanks @ryanmerolle, I think it's a great idea.
