### ISSUE TITLE
Devices never get added

### ISSUE THREAD

**Issue by Pzharyuk** [networktocode/ntc-netbox-plugin-onboarding#53]
### Environment
* Python version:  3.6.8
* NetBox version:  2.8.5
* ntc-netbox-plugin-onboarding version:  1.1.0

### Steps to Reproduce
1. https://netbox/plugins/onboarding/add/ - Add the device per instructions provided
2. Click on "Create"
3. Check device status under Onboarding Tasks or under the Admin panel

### Expected Behavior
Device to be added

### Observed Behavior
New device never gets added.

**Comment by dgarros** [comment]
Hi @Pzharyuk 
Do you have more information we can work with ? logs ? screenshots ? 
Not really sure how to help here

**Comment by Pzharyuk** [comment]
I removed the plugin and added it back in and now it's working perfectly. Must of been something with my initial installation.
