### ISSUE TITLE
default_device_status ignored

### ISSUE THREAD

**Issue by misch42** [networktocode/ntc-netbox-plugin-onboarding#58]
### Environment
* Python version:  3.6.8
* NetBox version:  2.8.7
* ntc-netbox-plugin-onboarding version:  1.1.0

Cofigured the onboarding plugin according to doc. Onboarding is working, but the option is ignored.

### Steps to Reproduce
1. Install
2. Configure
3. Run

### Expected Behavior

New device with given default status created in netbox.

### Observed Behavior
New device with state "Active" created in netbox.

netbox config is:
```
PLUGINS_CONFIG = {
  'netbox_onboarding': {
    'default_device_status': 'staged'
  }
}
```

**Comment by misch42** [comment]
Solved:

After changing the default_device_status in the config, you have to restart netbox AND netbox-rq

**Comment by dgarros** [comment]
Good point, we should probably add that to the readme
Glad you managed to fix your problem
