### ISSUE TITLE
cisco enable secret aren't passed through

### ISSUE THREAD

**Issue by lethalwp** [networktocode/ntc-netbox-plugin-onboarding#63]
The cisco enable secret isn't passed to the onboarding.
Thus "enable" doesn't work.

diff:
--- a/netbox_onboarding/worker.py
+++ b/netbox_onboarding/worker.py
@@ -29,6 +29,8 @@ def onboard_device(task_id, credentials):
     """Process a single OnboardingTask instance."""
     username = credentials.username
     password = credentials.password
+    secret = credentials.secret

     try:
         ot = OnboardingTask.objects.get(id=task_id)
@@ -43,7 +45,7 @@ def onboard_device(task_id, credentials):
         ot.status = OnboardingStatusChoices.STATUS_RUNNING
         ot.save()

-        netdev = NetdevKeeper(ot, username, password)
+        netdev = NetdevKeeper(ot, username, password, secret)
         nbk = NetboxKeeper(netdev=netdev)

         netdev.get_required_info()

**Comment by dgarros** [comment]
Fixed by #72
