### ISSUE TITLE
Failed Task - Restart Button

### ISSUE THREAD

**Issue by jvanderaa** [networktocode/ntc-netbox-plugin-onboarding#71]
### Environment
* Python version: 3.7.7
* NetBox version: 2.8.8
* ntc-netbox-plugin-onboarding version: 1.1

### Proposed Functionality

After a failed task it would be beneficial to have a restart button to retry the onboarding.

### Use Case

During initial use of the onboarding application your NetBox instance may require changes to the environment to get into a working state. It would be helpful to allow the changes to be made and then restart a failed task

**Comment by mzbroch** [comment]
This should be possible via table view as starting from v2.0 of plugin onboarding tasks are no longer subject for saving changed parameters during execution, thus original request is still available.

The button could be listed in a table view and will redirect to a new screen of OT modification with already existing initial values in the form.

**Comment by jvanderaa** [comment]
I think that it makes sense to use all the other same data other than credentials. Since we can't get them anyway, it would just be a restart with the same parameters that were entered originally.

**Comment by mzbroch** [comment]
There are currently two methods allowing for similar behaviour:
1. Create a Custom Link under `Admin Tab` in NetBox as follows:
`$MAIN_URL/plugins/onboarding/add/?&ip_address={{ obj.primary_ip.address.ip }}&site={{ obj.site.slug }}`
The custom link will be created for a Device model and will allow to provide IP and Site of the existing device thus simplifying the user experience

2. Copy & Pasting text block into Bulk-onboarding

With these two users should get similar to `restart` behaviour
