### ISSUE TITLE
Standardize 'port' parameter in Netdev Keeper

### ISSUE THREAD

**Issue by mzbroch** [networktocode/ntc-netbox-plugin-onboarding#80]
1. Add port support to `guess_netmiko_device_type`
2. Add port support to `napalm_device` in `get_onboarding_facts`

**Comment by dgarros** [comment]
I believe this is done in 2.0 but please can you confirm @mzbroch

**Comment by mzbroch** [comment]
> I believe this is done in 2.0 but please can you confirm @mzbroch

It's not yet done - we also have other similar requests captured in #102 and #103

**Comment by mzbroch** [comment]
Closed by #108
