### ISSUE TITLE
NetBox 2.9 - Bulk onboarding

### ISSUE THREAD

**Issue by berishap** [networktocode/ntc-netbox-plugin-onboarding#88]
Hello,

when trying do a bulk import, the following error occurs:

```
<class 'AttributeError'>

'OnboardingTask' object has no attribute '_cf'

Python version: 3.6.9
NetBox version: 2.9.2
```

Is this a bug or have I misconfigured the system?

Thank you.

**Comment by dgarros** [comment]
We are still in the process of testing this plugin with 2.9, so it's possible that something is not working as expected

_in the future please use the issue template proposed by Github_
