### ISSUE TITLE
Navigating to plugins/onboarding/import/ causes Server Error: 'OnboardingTask' object has no attribute '_cf'

### ISSUE THREAD

**Issue by LapineNoir** [networktocode/ntc-netbox-plugin-onboarding#96]
### Environment
* Python version:  3.8.2
* NetBox version:  2.9.4
* ntc-netbox-plugin-onboarding version:  1.3.0

### Steps to Reproduce
1. Navigate to plugins/onboarding/import/ or
2. From the Onboarding Tasks page, click on the "Import" button, or
3. From the Home page, click on Plugins > Onboarding Tasks > "Bulk Import" button.

### Expected Behavior
I expected the Onboarding Task Bulk Import page to be displayed.

### Observed Behavior
Received the following exception:

"Server Error

There was a problem with your request. Please contact an administrator.

The complete exception is provided below:

<class 'AttributeError'>

'OnboardingTask' object has no attribute '_cf'

Python version: 3.8.2
NetBox version: 2.9.4"

Screenshot also attached.

![onboarding](https://user-images.githubusercontent.com/30441968/94502658-895bbb80-01b9-11eb-9e7c-2be88f60763c.jpg)

**Comment by mzbroch** [comment]
NetBox 2.9 is not supported in the ntc-netbox-plugin-onboarding 1.3.

Support for NetBox 2.9 was provided in ntc-netbox-plugin-onboarding 2.0 which is currently in beta release and can be tested in `develop-2.0` branch.
